apiVersion: v1
kind: Service
metadata:
  name: jenkins-service # Changed name for consistency
  namespace: jenkins # Must match the deployment's namespace
  labels:
    app: jenkins
spec:
  type: NodePort # Expose Jenkins via NodePort
  selector:
    app: jenkins # Selects pods with label app: jenkins
  ports:
    - name: http
      protocol: TCP
      port: 8080 # Internal service port (common for Jenkins)
      targetPort: 8081 # Port on the pod (matches containerPort in deployment)
      nodePort: 30081 # External NodePort for Jenkins UI
    - name: jnlp
      protocol: TCP
      port: 50000 # Internal service port for JNLP
      targetPort: 50001 # Port on the pod for JNLP (matches containerPort in deployment)
      nodePort: 30000 # External NodePort for Jenkins JNLP