apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: jenkins
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
  - name: http
    port: 8080 # Keep the service's internal port
    targetPort: 8081 # Changed targetPort to match containerPort
    nodePort: 30081
  - name: jnlp
    port: 50000 # Keep the service's internal port
    targetPort: 50001 # Changed targetPort to match containerPort
    nodePort: 30000