apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce # This means it can only be mounted by one node at a time
  resources:
    requests:
      storage: 10Gi # Request 10GB of storage
  storageClassName: local-path # Uses the local-path StorageClass we installed