apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubetest-deployment
  namespace: kubetest-argo-docker
  labels:
    app: kubetest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubetest
  template:
    metadata:
      labels:
        app: kubetest
    spec:
      containers:
        - name: kubetest-container
          image: chackoabraham/kubetest-argo-docker:1ea23b9
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "100m"
              memory: "128Mi"
            requests:
              cpu: "50m"
              memory: "64Mi"
