apiVersion: v1
kind: Service
metadata:
  name: kubetest-service
  labels:
    app: kubetest
spec:
  selector:
    app: kubetest
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080  #  Added nodePort
  type: NodePort      # Changed to NodePort
