apiVersion: v1
kind: Service
metadata:
  name: kubetest-service
  namespace: kubetest-argo-docker # Add this line
  labels:
    app: kubetest
spec:
  selector:
    app: kubetest
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort