apiVersion: v1
kind: Service
metadata:
  name: kubetest-service
  labels:
    app: kubetest
spec:
  selector:
    app: kubetest
  ports:
    - protocol: TCP
      port: 80 # The port on which the Service will be exposed within the cluster
      targetPort: 80 # The port your container is listening on
  type: LoadBalancer # Use LoadBalancer if you are on a cloud provider that supports it
                   # For local testing or environments without a LoadBalancer, you can use NodePort or Ingress